### PR TITLE
don't compute version if directory is stale

### PR DESCRIPTION
**Pull request by mlilien**

### CODE REVIEW

**Review by FlorianReinhold — CHANGES_REQUESTED** [review]
the artifact dir should be gen/gitversion/ .

**Comment by mlilien** [comment]
> the artifact dir should be gen/gitversion/ .

okay. currently it doesnt make a difference. So it seems there is more meaning behind "gen" directory. If so, which is it?

**Comment by FlorianReinhold** [comment]
> > the artifact dir should be gen/gitversion/ .
> 
> okay. currently it doesnt make a difference. So it seems there is more meaning behind "gen" directory. If so, which is it?

yes, you're right. unfortunately, it hasn't been documented anywhere. 

basically, i want to achieve that all building blocks have the same interface to the outside, so they behave the same on the outside. the idea in this case is the following: 

Let's assume that two components are built in the building block. One component generates something in addition, then the current structure should look as follows:

build/comp1/
build/comp2/
gen/conp1/

in your example the gen directory gen/gitversion is mounted into the container (see mount section in the dobi-file). If you only take the gen root directory, as soon as something else is generated, the dobi rebuild mechanism will not work correctly.

**Review by FlorianReinhold — APPROVED** [review]
thx

**Pull request merged**
